import { MenuCategory, FoodType } from './types';

export const MENU_DATA: MenuCategory[] = [
  {
    name: 'Shawarma & BBQ',
    image: 'https://images.unsplash.com/photo-1629505491216-9351036037b5?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        subCategory: 'Shawarma',
        items: [
          { name: 'Chicken shawarma', price: 90 },
          { name: 'Mexican shawarma', price: 100 },
          { name: 'Schezwan shawarma', price: 110 },
          { name: 'Special shawarma', price: 140 },
          { name: 'Plate shawarma', price: 160 },
        ],
      },
      {
        subCategory: 'Barbeque',
        items: [
          { name: 'Red chilli BBQ', price: 'H 200 / F 360' },
          { name: 'Pepper BBQ', price: 'H 200 / F 360' },
          { name: 'Hariyali BBQ', price: 'H 240 / F 420' },
        ],
      },
      {
        subCategory: 'Extras',
        items: [
          { name: 'Extra Mayonnaise', price: 20 },
          { name: 'Extra Kuboose', price: 15 },
        ],
      },
    ],
  },
  {
    name: 'Sandwich',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    items: [
        { name: 'Veg Sandwich', price: 70, type: FoodType.VEG },
        { name: 'Veg Cheese Sandwich', price: 80, type: FoodType.VEG },
        { name: 'Panner Sandwich', price: 90, type: FoodType.VEG },
        { name: 'Cheese Corn Sandwich', price: 90, type: FoodType.VEG },
        { name: 'Schezwan Sandwich', price: 95, type: FoodType.VEG },
        { name: 'Schezwan Cheese Sandwich', price: 100, type: FoodType.VEG },
        { name: 'Paneer Masala Sandwich', price: 105, type: FoodType.VEG },
        { name: 'Nutella Sandwich', price: 110, type: FoodType.VEG },
        { name: 'Club Sandwich', price: 115, type: FoodType.VEG },
        { name: 'ZAN Special Sandwich', price: 125, type: FoodType.VEG },
        { name: 'Chicken Sandwich', price: 80, type: FoodType.NON_VEG },
        { name: 'Chicken Cheese Sandwich', price: 90, type: FoodType.NON_VEG },
        { name: 'Fried Chicken Schezwan Sandwich', price: 100, type: FoodType.NON_VEG },
        { name: 'Fried Chicken Schezwan Cheese Sandwich', price: 110, type: FoodType.NON_VEG },
        { name: 'Fried Chicken Masala Sandwich', price: 120, type: FoodType.NON_VEG },
        { name: 'Fried Chicken Club Sandwich', price: 130, type: FoodType.NON_VEG },
        { name: 'ZAN Special Chicken Sandwich', price: 150, type: FoodType.NON_VEG },
    ],
  },
  {
    name: 'Milkshakes',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
    items: [
      { name: 'Mexican Vanilla Shake', price: 50 },
      { name: 'Romantic Rose Shake', price: 55 },
      { name: 'Indian Banana Shake', price: 75 },
      { name: 'Malgova Mango Shake', price: 75 },
      { name: 'Spanish Strawberry Shake', price: 85 },
      { name: 'British Butterscotch Shake', price: 85 },
      { name: 'Colombian Rose Cooler Shake', price: 85 },
      { name: 'Caribbean Chocolate Shake', price: 95 },
      { name: 'Iranian Pista Shake', price: 95 },
      { name: 'Roman Fig Honey Shake', price: 95 },
      { name: 'Fujian Lychee Shake', price: 95 },
      { name: 'Arabian Dates Shake', price: 95 },
      { name: 'Russian Blackcurrent Shake', price: 95 },
      { name: 'Natural Tendercoconut Shake', price: 95 },
      { name: 'Asian Kesar Badam Shake', price: 95 },
      { name: 'Chile Cranberry Shake', price: 95 },
      { name: 'Polish Blue Berry Shake', price: 95 },
      {
        subCategory: 'Business Class',
        items: [
          { name: 'Punjabi Pan Shake', price: 105 },
          { name: 'Turkish Coffee Shake', price: 115 },
          { name: 'American Oreo Shake', price: 135 },
          { name: 'Kingdom Kit-Kat Shake', price: 145 },
          { name: 'Nutella Hazelnut Shake', price: 155 },
          { name: 'Brazilian Bubble Gum Shake', price: 165 },
          { name: "Italian Ferrer o' Cher Shake", price: 175 },
        ],
      },
    ],
  },
  {
    name: 'Quick Bites',
    image: 'https://images.unsplash.com/photo-1606131731446-5568d87113aa?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        subCategory: 'Rolls',
        items: [
          { name: 'Veg Roll', price: 75, type: FoodType.VEG },
          { name: 'Paneer Roll', price: 85, type: FoodType.VEG },
          { name: 'Crispy Chicken Roll', price: 100, type: FoodType.NON_VEG },
        ],
      },
      {
        subCategory: 'Zan Hot',
        items: [
          { name: 'Bread omelette', price: 50, type: FoodType.EGG },
          { name: 'Veg Cutlet', price: 70, type: FoodType.VEG },
          { name: 'French Fries', price: 80, type: FoodType.VEG },
          { name: 'Smiley Fries', price: 85, type: FoodType.VEG },
          { name: 'Peri peri Fries', price: 85, type: FoodType.VEG },
          { name: 'Masala Fries', price: 90, type: FoodType.VEG },
          { name: 'Cheese Corn Nuggets', price: 95, type: FoodType.VEG },
          { name: 'Chicken Nuggets', price: 100, type: FoodType.NON_VEG },
        ],
      },
    ],
  },
  {
    name: 'Maggi & Momos',
    image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0d06c1?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        subCategory: 'Maggi',
        items: [
          { name: 'Classic Maggi', price: 50, type: FoodType.VEG },
          { name: 'Peri Peri Maggi', price: 60, type: FoodType.VEG },
          { name: 'Schezwan Maggi', price: 70, type: FoodType.VEG },
          { name: 'Sweet corn Maggi', price: 70, type: FoodType.VEG },
          { name: 'Cheese Maggi', price: 80, type: FoodType.VEG },
          { name: 'Panner Maggi', price: 80, type: FoodType.VEG },
        ],
      },
      {
        subCategory: 'Momos',
        items: [
          { name: 'Fried Mix Veg Momos', price: 80, type: FoodType.VEG },
          { name: 'Fried Mushroom Momos', price: 90, type: FoodType.VEG },
          { name: 'Fried Paneer Momos', price: 95, type: FoodType.VEG },
          { name: 'Cheese Corn Momos', price: 100, type: FoodType.VEG },
          { name: 'Fried Chicken Momos', price: 110, type: FoodType.NON_VEG },
          { name: 'Chicken Cheese Momos', price: 120, type: FoodType.NON_VEG },
        ],
      },
    ],
  },
  {
    name: 'Fried Chicken',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    items: [
      { name: 'Fried Chicken Popcorn', price: 130, description: '10pc', type: FoodType.NON_VEG },
      { name: 'Fried Chicken Drumstick', price: 140, description: '2pc', type: FoodType.NON_VEG },
      { name: 'Fried Chicken Wings', price: 140, description: '3pc', type: FoodType.NON_VEG },
      { name: 'Chicken Lollipop', price: 170, description: '5pc', type: FoodType.NON_VEG },
      { name: 'Boneless Chicken Strips', price: 180, description: '5pc', type: FoodType.NON_VEG },
    ],
  },
  {
    name: 'Desserts & Juices',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        subCategory: 'Falooda',
        items: [
          { name: 'Royal Falooda', price: 95 },
          { name: 'Kulfi Falooda', price: 110 },
          { name: 'Dry Fruit Falooda', price: 135 },
          { name: 'Mixed Ice Cream Falooda', price: 150 },
        ],
      },
      {
        subCategory: 'Fresh Juice',
        items: [
          { name: 'Lemon', price: 40 },
          { name: 'Mosambi', price: 65 },
          { name: 'Orange', price: 80 },
          { name: 'Pomegranate', price: 90 },
          { name: 'Apple', price: 90 },
        ],
      },
      {
        subCategory: 'Ice Creams',
        items: [
          { name: 'Vanilla', price: 40 },
          { name: 'Strawberry', price: 55 },
          { name: 'Chocolate', price: 55 },
          { name: 'Mango', price: 55 },
          { name: 'Pista', price: 60 },
          { name: 'Butterscotch', price: 60 },
          { name: 'Blackcurrant', price: 60 },
        ],
      },
      {
        subCategory: 'Brownie',
        items: [
          { name: 'Brownie With Ice Cream', price: 100 },
          { name: 'Brownie With Kulfi', price: 110 },
          { name: 'Sizzler Brownie', price: 140 },
        ],
      },
    ],
  },
  {
    name: 'Burger',
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=800&q=80',
    items: [
      { name: 'Kids Burger', price: 65, type: FoodType.VEG },
      { name: 'Veg Classic Burger', price: 80, type: FoodType.VEG },
      { name: 'Cheese Corn Burger', price: 90, type: FoodType.VEG },
      { name: 'Loaded Paneer Burger', price: 100, type: FoodType.VEG },
      { name: 'Tikka Burger', price: 110, type: FoodType.VEG },
      { name: 'Fried Paneer Masala Burger', price: 120, type: FoodType.VEG },
      { name: 'Veg Tower Cheese Burger', price: 130, type: FoodType.VEG },
      { name: 'ZAN Special Burger', price: 150, type: FoodType.VEG },
      { name: 'BBQ Chicken Burger', price: 110, type: FoodType.NON_VEG },
      { name: 'BBQ Chicken Cheese Burger', price: 120, type: FoodType.NON_VEG },
      { name: 'Chicken Burger', price: 125, type: FoodType.NON_VEG },
      { name: 'Loaded Chicken Burger', price: 140, type: FoodType.NON_VEG },
      { name: 'Chicken Tower Burger', price: 150, type: FoodType.NON_VEG },
      { name: 'Fried Chicken Fried Paneer Burger', price: 170, type: FoodType.NON_VEG },
      { name: 'ZAN Special Chicken Burger', price: 150, type: FoodType.NON_VEG },
    ],
  },
  {
    name: 'Beverages',
    image: 'https://images.unsplash.com/photo-1551024709-0f23097521e9?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        subCategory: "Soda's & Mojito's",
        items: [
          { name: 'Deal Jaljira Lime Soda', price: 50 },
          { name: 'Digestive Lime Mint Soda', price: 60 },
          { name: 'Masala Soda', price: 65 },
          { name: 'Ginger Mint Soda', price: 65 },
          { name: 'Mango Mojo', price: 80 },
          { name: 'Hawaiian Mojito', price: 80 },
          { name: 'Straw Mojito', price: 90 },
          { name: 'Lych Mojito', price: 90 },
          { name: 'Dunken Blue Curacao', price: 100 },
          { name: 'Blue Berry Lych Mojo', price: 100 },
          { name: 'Mango Lychee Mojo', price: 100 },
        ],
      },
      {
        subCategory: 'Lassi',
        items: [
          { name: 'Sweet Lassi', price: 55 },
          { name: 'Banana Lassi', price: 65 },
          { name: 'Rose Lassi', price: 65 },
          { name: 'Strawberry Lassi', price: 65 },
          { name: 'Mango Lassi', price: 75 },
          { name: 'Black current Lassi', price: 75 },
          { name: 'Chocolate Lassi', price: 85 },
          { name: 'Kesar & Dry Badam Lassi', price: 95 },
          { name: 'Dry Fruits Lassi', price: 110 },
        ],
      },
    ],
  },
  {
    name: 'Pizza',
    image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=800&q=80',
    items: [
      { name: 'Margarita Pizza', price: 95, type: FoodType.VEG },
      { name: 'Mexican Pizza', price: 110, type: FoodType.VEG },
      { name: 'Cheese Corn Pizza', price: 125, type: FoodType.VEG },
      { name: 'Double Cheese Pizza', price: 140, type: FoodType.VEG },
      { name: 'Veggie Mania', price: 140, type: FoodType.VEG },
      { name: 'Olive Pizza', price: 145, type: FoodType.VEG },
      { name: 'Paneer Tikka Pizza', price: 150, type: FoodType.VEG },
      { name: 'Fried Paneer Pizza', price: 150, type: FoodType.VEG },
      { name: 'Chicken Pizza', price: 155, type: FoodType.NON_VEG },
      { name: 'Loaded Chicken Olive Pizza', price: 165, type: FoodType.NON_VEG },
      { name: 'BBQ Pizza', price: 170, type: FoodType.NON_VEG },
      { name: 'Chicken Layer Pizza', price: 180, type: FoodType.NON_VEG },
    ],
  },
];